---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: apisix
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.apiseven.com

---
# https://artifacthub.io/packages/helm/apisix/apisix
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apisix
  namespace: ingress-apisix
spec:
  interval: 5m
  chart:
    spec:
      chart: apisix
      version: "2.11.4"
      sourceRef:
        kind: HelmRepository
        name: apisix
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  values:
    etcd:
      replicaCount: 1
      image:
        registry: docker.io
        repository: bitnamilegacy/etcd
        tag: 3.5.10-debian-11-r2
        pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      externalTrafficPolicy: null
      http:
        enabled: true
        servicePort: 80
        containerPort: 9080
      tls:
        servicePort: 443
    apisix:
      ssl:
        enabled: true
        containerPort: 9443
    ingress-controller:
      enabled: true
      config:
        kubernetes:
          enableGatewayAPI: true
        apisix:
          serviceNamespace: ingress-apisix
        ingressPublishService: "ingress-apisix/apisix-gateway"
    admin:
      secretName: apisix-admin-credentials