---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: dockerhub-pat
  namespace: inventory-app
spec:
  encryptedData:
    .dockerconfigjson: AgCZRZ0RHFjogdsD8gSJ1+bjFZyXHFs4UgemBrUyzI/ASRMqmIPo/U+9fpicZTF2/tiwPdcp0qh37+uNi5RhI3dyZPUZ5J8GCGVEmWrDbYQRi/hgIXjdS4Vpc+QIYQUc6Izw6HiNue2H9zRHysJa7tj/lKJFVEhwYh+8yBAgYGK393H8ckEQBU/n4ZTdrlRJhWkWKRI4b+XjPpeo0SoHM123bpmyjYE1lmI8GgtYlbzS98uYvRUnDBCYKQMh+hMAhgiphmu+kWlwqptl3ytiS8o5IwdUgX9RH7hyPEhmXEIwWbpJ5umqVc3hUasszzhQ70uC0lrYwGYAZQVqZPMZLhauxAWSP9I7qM9d9MG2xgRJZFSM98qRdI934LUKS1QBLouADodv8rqmqnUdnfuogpqihjpc8FW7xYCvVzvr4+wP/KLx1yjWLpqbWyxllsttC2M6ClBSq2vQhn70pDDwERhJXuz2q6a0PJt9u5g1CqJlsUmFiOiEuB9EycNQrYmurLqb4UeOTdLmLAi3TL70NtZtUslhKRN4X8l+qFo4s8HNy7Z66WhOZ/xUTtTUyGDv2mAKRD+qcmbYYaPRJatqReMLAqQ3nF7wMRZcZHX+phAM4lJK1sAUaHAlSfFUcg2lcXzLYB2NjLJB1P31/DahoIXeTT0Q3b5ML94KxeJhBbfFyom/hrwxMddm+ahMPPNeonECIhkkSg5ObO1eTlI6qASSr/G46VrqSRK/8DkvFHJ6BIfxDOoyBW2Cjs/3OFpMtbWzSTOSo/tDhLaONRrxavfpfaH5sDGaN+Npz5dhPdWpa758qYyn6s5QIb/cUsgkIDGUr0eBnVV0IlCUllmeAK1BDlvHrIdcshwgJ3FBDZF6ln2BYJ48+tsHSlVxxiOg+BG/cFbCsF/WCbLPQl9UzBsgGabatxifYwTEdMisZl2FUczl/BBH1BlV3l7IPHGFk0vVfcOv9bP1NWAKesORlBlV9GbLYkhL1ZfwvCux9v3IA+mpS3GGxJzIYVe77Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: dockerhub-pat
      namespace: inventory-app
    type: kubernetes.io/dockerconfigjson