apiVersion: v1
kind: Service
metadata:
  name: inventory-app-backend
  namespace: inventory-app
spec:
  selector:
    app: inventory-app-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP