---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: inventory-app-frontend
  namespace: inventory-app
spec:
  image: srgottfried/pulpo-inventory-app-frontend
  interval: 1m
